In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.stats.proportion import proportions_ztest
from statsmodels.stats.proportion import confint_proportions_2indep

data loading

In [21]:
import pandas as pd

df = pd.read_csv("YRBS_2007.csv")

df.head()

,RaceEth,HowOldAreYou,WhatIsYourSex,InWhatGradeAreYou,AreYouHispanicOrLatino,WhatIsYourRace,HowTallAreYouWithoutShoesInMeters,HowMuchDoYouWeighWithoutShoesInKG,BicyleHelmetUse,SeatBeltUse,...,InjuredWhileExercising,HIVTesting,SunscreenUse,SunProtection,Sleep,HealthInGeneral,BMIPCT,weight,stratum,psu
0,7.0,4.0,2.0,2.0,1.0,C,NaN,NaN,2.0,1.0,...,3.0,2.0,1.0,1.0,5.0,3.0,NaN,1.5104,101,11030
1,5.0,7.0,2.0,2.0,2.0,E,1.70,68.04,4.0,4.0,...,2.0,3.0,1.0,5.0,4.0,3.0,66.531824,1.8559,101,11030
2,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,5.0,3.0,...,2.0,3.0,2.0,1.0,1.0,1.0,NaN,1.8559,101,11030
3,7.0,1.0,1.0,1.0,1.0,A,1.63,79.38,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,98.174319,1.3264,101,11030
4,7.0,1.0,1.0,5.0,1.0,B,NaN,NaN,6.0,5.0,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.3264,101,11030

variable selection

In [24]:
df2 = df[['WhatIsYourSex', 'CurrentCigaretteUse']].copy()

df2.head()

   WhatIsYourSex  CurrentCigaretteUse
0            2.0                  7.0
1            2.0                  NaN
2            2.0                  NaN
3            1.0                  1.0
4            1.0                  1.0

recoding

In [26]:
df2['Sex_Recode'] = df2['WhatIsYourSex'].map({
    1: 'Male',
    2: 'Female'
})

df2[['WhatIsYourSex', 'Sex_Recode']].head()

   WhatIsYourSex Sex_Recode
0            2.0     Female
1            2.0     Female
2            2.0     Female
3            1.0       Male
4            1.0       Male

In [28]:
df2['CurrentCigaretteUse_Recode'] = np.where(
    df2['CurrentCigaretteUse'] == 1,
    0,
    1
)

df2[['CurrentCigaretteUse', 'CurrentCigaretteUse_Recode']].head()

   CurrentCigaretteUse  CurrentCigaretteUse_Recode
0                  7.0                           1
1                  NaN                           1
2                  NaN                           1
3                  1.0                           0
4                  1.0                           0

descriptive comparison

In [30]:
summary = df2.groupby('Sex_Recode')['CurrentCigaretteUse_Recode'].agg(
    Sample_Size='count',
    Current_Smokers='sum',
    Proportion='mean'
)
summary['Percentage'] = summary['Proportion'] * 100
summary

            Sample_Size  Current_Smokers  Proportion  Percentage
Sex_Recode
Female             6992             1838    0.262872   26.287185
Male               7036             1463    0.207931   20.793064

two-sample inference

In [32]:
male = df2[df2['Sex_Recode'] == 'Male']
female = df2[df2['Sex_Recode'] == 'Female']

count = [
    male['CurrentCigaretteUse_Recode'].sum(),
    female['CurrentCigaretteUse_Recode'].sum()
]

nobs = [
    len(male),
    len(female)
]

z_stat, p_value = proportions_ztest(count, nobs)

print("Male smokers:", count[0])
print("Female smokers:", count[1])
print("Male sample size:", nobs[0])
print("Female sample size:", nobs[1])
print("z statistic:", z_stat)
print("p-value:", p_value)

Male smokers: 1463
Female smokers: 1838
Male sample size: 7036
Female sample size: 6992
z statistic: -7.67004355633165
p-value: 1.7193795348649527e-14

interpretation

In [36]:
print("Conclusion: Fail to reject H0. There is not sufficient evidence that the proportions are different.")

Conclusion: Fail to reject H0. There is not sufficient evidence that the proportions are different.