In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.stats.proportion import proportions_ztest
from statsmodels.stats.proportion import confint_proportions_2indep

import pandas as pd
df = pd.read_csv("YRBS_2007.csv")
df.head()

,RaceEth,HowOldAreYou,WhatIsYourSex,InWhatGradeAreYou,AreYouHispanicOrLatino,WhatIsYourRace,HowTallAreYouWithoutShoesInMeters,HowMuchDoYouWeighWithoutShoesInKG,BicyleHelmetUse,SeatBeltUse,...,InjuredWhileExercising,HIVTesting,SunscreenUse,SunProtection,Sleep,HealthInGeneral,BMIPCT,weight,stratum,psu
0,7.0,4.0,2.0,2.0,1.0,C,NaN,NaN,2.0,1.0,...,3.0,2.0,1.0,1.0,5.0,3.0,NaN,1.5104,101,11030
1,5.0,7.0,2.0,2.0,2.0,E,1.70,68.04,4.0,4.0,...,2.0,3.0,1.0,5.0,4.0,3.0,66.531824,1.8559,101,11030
2,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,5.0,3.0,...,2.0,3.0,2.0,1.0,1.0,1.0,NaN,1.8559,101,11030
3,7.0,1.0,1.0,1.0,1.0,A,1.63,79.38,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,98.174319,1.3264,101,11030
4,7.0,1.0,1.0,5.0,1.0,B,NaN,NaN,6.0,5.0,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.3264,101,11030

In [27]:
df2 = df[['WhatIsYourSex', 'CurrentCigaretteUse']].copy()

df2.head()

   WhatIsYourSex  CurrentCigaretteUse
0            2.0                  7.0
1            2.0                  NaN
2            2.0                  NaN
3            1.0                  1.0
4            1.0                  1.0

In [29]:
df2 = df2.dropna()

df2.shape

(13312, 2)

In [31]:
df2['Sex_Recode'] = df2['WhatIsYourSex'].map({
    1: 'Male',
    2: 'Female'
})

df2[['WhatIsYourSex', 'Sex_Recode']].head()

   WhatIsYourSex Sex_Recode
0            2.0     Female
3            1.0       Male
4            1.0       Male
5            1.0       Male
6            1.0       Male

In [33]:
df2['CurrentCigaretteUse_Recode'] = np.where(
    df2['CurrentCigaretteUse'] == 1,
    0,
    1
)

df2[['CurrentCigaretteUse', 'CurrentCigaretteUse_Recode']].head()

   CurrentCigaretteUse  CurrentCigaretteUse_Recode
0                  7.0                           1
3                  1.0                           0
4                  1.0                           0
5                  1.0                           0
6                  1.0                           0

In [35]:
df2 = df2.dropna(subset=['Sex_Recode'])

df2['Sex_Recode'].value_counts()

Sex_Recode
Male      6740
Female    6572
Name: count, dtype: int64